// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWU_325qUDpFy4aViixa5JCheo15-ll-c',
    appId: '1:700279582470:web:7e227a0f6d0fb67271f887',
    messagingSenderId: '700279582470',
    projectId: 'performance-app-82781',
    authDomain: 'performance-app-82781.firebaseapp.com',
    storageBucket: 'performance-app-82781.firebasestorage.app',
    measurementId: 'G-XTL2Q35DLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_6QWDYknbszqNqBGZYgIb11aR2qPb9A',
    appId: '1:700279582470:android:eaefbad53608485c71f887',
    messagingSenderId: '700279582470',
    projectId: 'performance-app-82781',
    storageBucket: 'performance-app-82781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx9kSsa1QebxQcE2g6rRp57eIElU8jxZk',
    appId: '1:700279582470:ios:b69acef378e9deb571f887',
    messagingSenderId: '700279582470',
    projectId: 'performance-app-82781',
    storageBucket: 'performance-app-82781.firebasestorage.app',
    iosBundleId: 'com.example.staffWorkTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx9kSsa1QebxQcE2g6rRp57eIElU8jxZk',
    appId: '1:700279582470:ios:b69acef378e9deb571f887',
    messagingSenderId: '700279582470',
    projectId: 'performance-app-82781',
    storageBucket: 'performance-app-82781.firebasestorage.app',
    iosBundleId: 'com.example.staffWorkTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWU_325qUDpFy4aViixa5JCheo15-ll-c',
    appId: '1:700279582470:web:6bfa1a29258654c871f887',
    messagingSenderId: '700279582470',
    projectId: 'performance-app-82781',
    authDomain: 'performance-app-82781.firebaseapp.com',
    storageBucket: 'performance-app-82781.firebasestorage.app',
    measurementId: 'G-5HWDFNKJ6V',
  );
}
